name: Weekly GitHub Issues Report

on:
  push:
    branches:
      - setup-actions
  # schedule:
  #   # Runs every Monday at 10:00 AM IST (i.e. 04:30 UTC)
  #   - cron: '30 4 * * 1'
  workflow_dispatch:

jobs:
  generate-issue-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openpyxl requests

      - name: Run issue report script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          OWNER: actions
          REPO: setup-python
        run: python scripts/extract_issues_setup.py
